@baseUrl=http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name":"Dener Araujo",
  "email":"dener2@dener.com",
  "password":"123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email":"dener2@dener.com",
  "password":"123456"
}

###

# @name create_meal
POST {{baseUrl}}/meals
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
      "name": "New Meal",
      "description":"New description",
      "date":"2024-01-01",
      "hour":"14:00:00",
      "isOnTheDiet": true
}

###